services:
  - type: web
    name: questlog-backend
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd apps/backend && pnpm install && pnpm prisma generate && pnpm build
    startCommand: cd apps/backend && pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
